list p=18f458
#include <p18f458.inc>
;;;;;;DEFINEING LABLES==================================
Lcd_data equ PORTD
Lcd_CTRL equ PORTC
RS EQU RC0
RW EQU RC1
EN EQU RC2
COUNT EQU 0X20
COUNT1 EQU 0X21
ISRC EQU 0X22

;;;;;; ORGINAL LOCATIONS================================
ORG 0X00
GOTO MAIN
ORG 0X08
GOTO ISR
;;;;;; MAIN=============================================
MAIN
;;;;;PORTS INTERFACEING
BANKSEL TRISD
CLRF TRISD
BANKSEL TRISC
CLRF TRISC
BANKSEL TRISB
movlw 0xF0
movwf TRISB
BANKSEL TRISA
CLRF TRISA
;;;;;;;PORTB PULLUP
BCF INTCON2,RBPU
;;;;;;;TIMERON
BANKSEL T1CON
MOVLW   0x31       
MOVWF   T1CON
BANKSEL TMR1L
MOVLW 0X00
MOVWF TMR1H       
MOVLW 0X00 
MOVWF TMR1L
BSF T1CON, TMR1ON 
;;;;;;;TIMER INTERUPTS
BSF INTCON, GIE
BSF PIE1, TMR1IE  
BSF INTCON, PEIE  

;;;;;;;LCD INTERFACING
BCF Lcd_data,EN
CALL LDELAY
MOVLW 0X38
CALL COMWRT
CALL LDELAY
MOVLW 0X0C
CALL COMWRT
CALL DELAY
MOVLW 0x80
CALL COMWRT  
CALL DELAY 
MOVLW 'E'
CALL DATAWRT
MOVLW 'N'  
CALL DATAWRT  
CALL DELAY  
MOVLW 'T'
CALL DATAWRT
MOVLW 'E'  
CALL DATAWRT  
MOVLW 'R'  
CALL DATAWRT  
MOVLW ' '  
CALL DATAWRT  
MOVLW 'P'  
CALL DATAWRT  
MOVLW 'I'  
CALL DATAWRT  
MOVLW 'N'  
CALL DATAWRT  
MOVLW ' '  
CALL DATAWRT
MOVLW '*'  
CALL DATAWRT  
MOVLW '*'  
CALL DATAWRT  
MOVLW '*'  
CALL DATAWRT  
MOVLW '*'  
CALL DATAWRT  
MOVLW ' '
CALL DATAWRT 
MOVLW ' '
CALL DATAWRT     
MOVLW 0XC0
CALL COMWRT 

;;;;;;;;;;;;;;;;;;;;;;;;;;KEY MAIN LOOP================================
key1
MOVLW 0XFE
movwf PORTB
BTFSS PORTB,0
goto checkcol
bra ROW1
checkcol
BTFSS PORTB,5
goto LCD0
BRA ROW1
;R1C0
ROW1
MOVLW 0XFD
movwf PORTB
BTFSS PORTB,1
goto checkcol2
bra ROW2
checkcol2
BTFSS PORTB,5
goto LCD1
BRA ROW2
;R2C0
ROW2
MOVLW 0XFB
movwf PORTB
BTFSS PORTB,2
goto checkcol3
BRA ROW3
checkcol3
BTFSS PORTB,5
goto LCD2
BRA ROW3
;R3C0
ROW3
MOVLW 0XF7
movwf PORTB
BTFSS PORTB,3
goto checkcol4
checkcol4
BTFSS PORTB,5
goto ENTER
BRA R0C1
;R0C1
R0C1
MOVLW 0XFE
movwf PORTB
BTFSS PORTB,0
goto checkco4
BRA R1C1
checkco4
BTFSS PORTB,6
goto LCD4
BRA R1C1
;R1C1
R1C1
MOVLW 0XFD
movwf PORTB
BTFSS PORTB,1
goto checkcol5
BRA R2C1
checkcol5
BTFSS PORTB,6
goto LCD5
BRA R2C1
;R2C1
R2C1
MOVLW 0XFB
movwf PORTB
BTFSS PORTB,2
goto checkcol6
BRA R3C1
checkcol6
BTFSS PORTB,6
goto LCD6
BRA R3C1
;R3C1
R3C1
MOVLW 0XF7
movwf PORTB
BTFSS PORTB,3
goto checkcol7
BRA R0C2
checkcol7
BTFSS PORTB,6
goto LCD7
BRA R0C2
;R0C2
R0C2
MOVLW 0XFE
movwf PORTB
BTFSS PORTB,0
goto checkco8
BRA R1C2
checkco8
BTFSS PORTB,7
goto LCD8
BRA R1C2
;R1C2
R1C2
MOVLW 0XFD
movwf PORTB
BTFSS PORTB,1
goto checkcol9
BRA R2C2
checkcol9
BTFSS PORTB,7
goto LCD9
BRA R2C2
;R2C2
R2C2
MOVLW 0XFB
movwf PORTB
BTFSS PORTB,2
goto checkcol10
BRA R3C2
checkcol10
BTFSS PORTB,7
goto LCD10
BRA R3C2
;R3C2
R3C2
MOVLW 0XF7
movwf PORTB
BTFSS PORTB,3
goto checkcol11
checkcol11
BTFSS PORTB,7
goto LCD11
BRA key1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;LCD KEY DISPLAYS================================
;;;;;;LCDS ARE GIVEN FORCED LOCATIONS AS OUR LOGIC IS LIKE A GAME YOU HAVE TO CHOOSE THE RIGHT KEYS FROM 11 KEYS FOR THE GATE TO OPEN ITS LIKE MATCH THE RIGHT KEYS
;;;;;; ALSO LCDS ARE LIKE LOCKS IN OUR CASE! AND SAVED PIN IS 1,5,8,0 THESE PINS ARE GIVEN PORTC,4,5,6,7 LOCATION IF ALL OF THEM ARE SET AND ENTERED IT GIVES ACCESS
;;;;;; WHILE ALL THE OTHER KEYS ARE GIVEN PORTC,3 LOCATIONS IF IT IS SET THE "WRONG PIN TIMEUP" IS DISPLAYED AS OUR CODE RUN ON INFINITY TIME IT ONLY STOPS WHEN EITHER
;;;;;; ACCESS GRANTED,ACCESS DENIED OR WRONG PIN TIMEUP IS ACTIVATED. IF YOU PRESS 1,5 AND PRESS ENTER IT DISPLAYS ACCESS DENIED AS 4 KEYS WERE NOT PRESSED AND 2 OFF THEM 
;;;;;; WERE CORRECT, ACCESS DENIED WILL ONLY OCCURE IF YOU ONT FILL THE RIGHT KEYS PERFECTLY
;LCD0
LCD0:
BSF PORTC,5
movlw 0xC0
call COMWRT
MOVLW '1'
CALL DATAWRT
CALL DELAY
return
;LCD1
LCD1:
bsf PORTC,3     ;LINKED TO PORTC,3
movlw 0xC1
call COMWRT
MOVLW '4'
CALL DATAWRT
CALL DELAY
RETURN 
;LCD2
LCD2:
bsf PORTC,3     ;LINKED TO PORTC,3
movlw 0xC2
call COMWRT
MOVLW '7'
CALL DATAWRT
CALL DELAY
RETURN 
;;;;;;;;;;;;;;;;;;;;;; ENTER KEY;;;;;;;;;;;;;;;;;;;
ENTER
BTFSS PORTC, 4       ; Check if PORTC.4 is set
GOTO ACCESS_DENIED   ; If not, go to "Access Denied"
BTFSS PORTC, 5       ; Check if PORTC.5 is set
GOTO ACCESS_DENIED   ; If not, go to "Access Denied"
BTFSS PORTC, 6       ; Check if PORTC.6 is set
GOTO ACCESS_DENIED   ; If not, go to "Access Denied"
BTFSS PORTC, 7       ; Check if PORTC.7 is set
GOTO ACCESS_DENIED   ; If not, go to "Access Denied"
BTFSC PORTC, 3       ; Check if PORTC.3 is CLEAR
GOTO ACCESS_DENIED   ; If not, go to "Access Denied"
; If all pins are set, access is granted
CALL DISP            ; Call the DISP subroutine to display "Access Granted"
GOTO key1           

;;;;;;;;; ACCESS DENIED===========================
ACCESS_DENIED
BSF PORTA,1          ; LED RED ON TO INDICATE ACCESS DENIED
MOVLW 0XC0           
CALL COMWRT
CALL DELAY
MOVLW ' '
CALL DATAWRT
MOVLW 'A'
CALL DATAWRT
MOVLW 'C'
CALL DATAWRT
MOVLW 'C'
CALL DATAWRT
CALL DELAY
MOVLW 'E'
CALL DATAWRT
MOVLW 'S'
CALL DATAWRT
MOVLW 'S'
CALL DATAWRT
MOVLW ' '
CALL DATAWRT
MOVLW 'D'
CALL DATAWRT
MOVLW 'E'
CALL DATAWRT
MOVLW 'M'
CALL DATAWRT
MOVLW 'I'
CALL DATAWRT
MOVLW 'E'
CALL DATAWRT
MOVLW 'D'
CALL DATAWRT
CALL DELAY 
BRA key1
;;;;;;;;; ACCESS GRANTED====================================================
DISP
BSF PORTA,0          ; LED GREEN ON TO INDICATE ACCESS GRANTED
MOVLW 0XC0          
CALL COMWRT
CALL DELAY
MOVLW ' '
CALL DATAWRT
MOVLW 'A'
CALL DATAWRT
MOVLW 'C'
CALL DATAWRT
MOVLW 'C'
CALL DATAWRT
CALL DELAY
MOVLW 'E'
CALL DATAWRT
MOVLW 'S'
CALL DATAWRT
MOVLW 'S'
CALL DATAWRT
MOVLW ' '
CALL DATAWRT
MOVLW 'G'
CALL DATAWRT
MOVLW 'R'
CALL DATAWRT
MOVLW 'A'
CALL DATAWRT
MOVLW 'N'
CALL DATAWRT
MOVLW 'T'
CALL DATAWRT
MOVLW 'E'
CALL DATAWRT
MOVLW 'D'
CALL DATAWRT
CALL DELAY 
BRA key1                     ; BRA TO LOOP

;;;;;;;;;;;;;;;;;;;;;;NOT USED AS * IS OUR ENTER KEY =====================
;LCD3:
;movlw 0xC3
;call COMWRT
;MOVLW '*'
;CALL DATAWRT
;CALL DELAY
;RETURN 

;LCD4
LCD4:
bsf PORTC,3;    LINKED TO PORTC,3
movlw 0xC4
call COMWRT
MOVLW '2'
CALL DATAWRT
CALL DELAY
return
;LCD5
LCD5:
BSF PORTC,4
movlw 0xC5
call COMWRT
MOVLW '5'
CALL DATAWRT
CALL DELAY
RETURN 
;LCD6
LCD6:
BSF PORTC,6
movlw 0xC6
call COMWRT
MOVLW '8'
CALL DATAWRT
CALL DELAY
RETURN 
;LCD7
LCD7:
BSF PORTC,7
movlw 0xC7
call COMWRT
MOVLW '0'
CALL DATAWRT
CALL DELAY
RETURN 
;LCD8
LCD8:
BSF PORTC,3;   LINKED TO PORTC,3
movlw 0xC8
call COMWRT
MOVLW '3'
CALL DATAWRT
CALL DELAY
return
;LCD9
LCD9:
bsf PORTC,3;   LINKED TO PORTC,3
movlw 0xC9
call COMWRT
MOVLW '6'
CALL DATAWRT
CALL DELAY
RETURN 
;LCD10
LCD10:
bsf PORTC,3;   LINKED TO PORTC,3
movlw 0xCA
call COMWRT
MOVLW '9'
CALL DATAWRT
CALL DELAY
RETURN 
;LCD11
LCD11:
bsf PORTC,3;   LINKED TO PORTC,3
movlw 0xCB
call COMWRT
MOVLW '#'
CALL DATAWRT
CALL DELAY
RETURN 
;;;;;;;;;;; INTRUPT SERVICE ROUTINE TO DISPLAY WRONG PIN TIME UP
ISR
BTFSS   INTCON, TMR1IF
RETFIE
BCF     INTCON, TMR1IF
BTFSC PORTC,3
GOTO LOOP1
bra key1
LOOP1
GOTO TIMEUP
;;;;;;;;;;;;;;;;;;;;;;;;; DISPLAY WRONG PIN TIMEUP
TIMEUP
MOVLW 0X38
CALL COMWRT
CALL LDELAY
MOVLW 0X0f
CALL COMWRT
CALL DELAY
MOVLW 0xC0
CALL COMWRT  
CALL DELAY 
MOVLW 'W'
CALL DATAWRT
MOVLW 'R'  
CALL DATAWRT  
CALL DELAY  
MOVLW 'O'
CALL DATAWRT
MOVLW 'N'  
CALL DATAWRT  
MOVLW 'G'  
CALL DATAWRT  
MOVLW ' '  
CALL DATAWRT  
MOVLW 'P'  
CALL DATAWRT  
MOVLW 'I'  
CALL DATAWRT  
MOVLW 'N'  
CALL DATAWRT  
MOVLW ' '  
CALL DATAWRT  
MOVLW 'T'  
CALL DATAWRT  
MOVLW 'I'  
CALL DATAWRT  
MOVLW 'M'  
CALL DATAWRT  
MOVLW 'E'  
CALL DATAWRT  
MOVLW 'U'  
CALL DATAWRT  
MOVLW 'P'  
CALL DATAWRT
btg PORTA,2 ;  BLUE LED ON TO INCICATE WRONG PIN
bra key1
;;;;;;;;;;;;;; COMMAND WRITE FOR LED====================================
COMWRT 
MOVWF Lcd_data  
BCF Lcd_CTRL, RS  
BCF Lcd_CTRL, RW  
BSF Lcd_CTRL, EN  
CALL SDELAY  
BCF Lcd_CTRL, EN  
RETURN  
;;;;;;;;;;;;;; DATAWRITE FOR LED============================================
DATAWRT 
MOVWF Lcd_data  
BSF Lcd_CTRL, RS  
BCF Lcd_CTRL, RW  
BSF Lcd_CTRL, EN  
CALL SDELAY  
BCF Lcd_CTRL, EN  
RETURN 
;;;;;;;;;;;;;; DELAYS=======================================================
LDELAY
MOVLW d'30'
MOVWF COUNT
loop1
DECFSZ  COUNT, f
GOTO    loop1
RETURN
SDELAY:
MOVLW d'20'
MOVWF COUNT
loop2:
DECFSZ  COUNT, f
GOTO    loop2
RETURN
DELAY:
MOVLW d'10'
MOVWF COUNT
loop3:
DECFSZ   COUNT, f
GOTO    loop3
RETURN
;============================      END OF PROGRAM     =======================
END


